name: Threatrix Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Threatrix Cloud Scan (API-based)
        run: |
          curl -X POST "https://api.threatrix.io/scan" \
            -H "Authorization: Bearer ${{ secrets.THREATRIX_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "eid": "${{ secrets.THREATRIX_EID }}",
                  "oid": "${{ secrets.THREATRIX_OID }}",
                  "app_name": "${{ github.repository }}",
                  "branch": "${{ github.ref }}",
                  "scm_token": "${{ secrets.TOKEN }}"
                }'
